09-03 12:19:42 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "TERMIN" not found; SQL statement:
insert into Termin (id, titel, beschreibung, zeitPunkt, ort) values (null, ?, ?, ?, ?) [42102-168]
09-03 12:19:42 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "TERMIN" not found; SQL statement:
insert into Termin (id, titel, beschreibung, zeitPunkt, ort) values (null, ?, ?, ?, ?) [42102-168]
09-04 16:42:45 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Table "PERSON" not found; SQL statement:

    alter table Person 
        drop constraint FK8E488775C4AC44E0 [42102-168]
09-04 17:06:37 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK8E488775FC13770" not found; SQL statement:

    alter table Person 
        drop constraint FK8E488775FC13770 [90057-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:40)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at org.hibernate.tool.hbm2ddl.DatabaseExporter.export(DatabaseExporter.java:64)
	at org.hibernate.tool.hbm2ddl.SchemaExport.perform(SchemaExport.java:418)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:372)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:304)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:293)
	at de.zeunerds.meat.usermanagement.server.dao.AccountTest.setUp(AccountTest.java:22)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
09-07 10:36:12 jdbc[2]: exception
org.h2.jdbc.JdbcSQLException: Column "TEST" not found; SQL statement:
select account0_.pkey as pkey0_, account0_.password as password0_, account0_.name as name0_, account0_.firstname as firstname0_, account0_.username as username0_ from Account account0_ where account0_.username=test [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.expression.Comparison.optimize(Comparison.java:161)
	at org.h2.command.dml.Select.prepare(Select.java:802)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:74)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:264)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.hibernate.engine.jdbc.internal.proxy.ConnectionProxyHandler.continueInvocation(ConnectionProxyHandler.java:138)
	at org.hibernate.engine.jdbc.internal.proxy.AbstractProxyHandler.invoke(AbstractProxyHandler.java:81)
	at $Proxy4.prepareStatement(Unknown Source)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:147)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:166)
	at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:145)
	at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:1720)
	at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:1697)
	at org.hibernate.loader.Loader.doQuery(Loader.java:832)
	at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:293)
	at org.hibernate.loader.Loader.doList(Loader.java:2382)
	at org.hibernate.loader.Loader.doList(Loader.java:2368)
	at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2198)
	at org.hibernate.loader.Loader.list(Loader.java:2193)
	at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:470)
	at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:355)
	at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:195)
	at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1248)
	at org.hibernate.internal.QueryImpl.list(QueryImpl.java:101)
	at de.zeunerds.meat.server.usermanagement.dao.UsermanagementService.loadAccount(UsermanagementService.java:48)
	at de.zeunerds.meat.server.usermanagement.logic.AccountLogic.loadAccount(AccountLogic.java:26)
	at de.zeunerds.meat.server.usermanagement.access.AccountAccessImpl.loadAccount(AccountAccessImpl.java:50)
	at de.zeunerds.meat.server.usermanagement.access.AccountAccessTest.testLoadAccount(AccountAccessTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
09-07 10:40:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK8E488775306753E6" not found; SQL statement:

    alter table Person 
        drop constraint FK8E488775306753E6 [90057-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:40)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at org.hibernate.tool.hbm2ddl.DatabaseExporter.export(DatabaseExporter.java:64)
	at org.hibernate.tool.hbm2ddl.SchemaExport.perform(SchemaExport.java:418)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:372)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:304)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:293)
	at de.zeunerds.meat.server.HibernateUtils.generateSchema(HibernateUtils.java:49)
	at de.zeunerds.meat.server.usermanagement.access.AccountAccessTest.setUp(AccountAccessTest.java:18)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
09-07 10:40:46 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Constraint "FK8E488775E5526156" not found; SQL statement:

    alter table Person 
        drop constraint FK8E488775E5526156 [90057-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:40)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.jdbc.JdbcStatement.executeUpdateInternal(JdbcStatement.java:125)
	at org.h2.jdbc.JdbcStatement.executeUpdate(JdbcStatement.java:110)
	at org.hibernate.tool.hbm2ddl.DatabaseExporter.export(DatabaseExporter.java:64)
	at org.hibernate.tool.hbm2ddl.SchemaExport.perform(SchemaExport.java:418)
	at org.hibernate.tool.hbm2ddl.SchemaExport.execute(SchemaExport.java:372)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:304)
	at org.hibernate.tool.hbm2ddl.SchemaExport.create(SchemaExport.java:293)
	at de.zeunerds.meat.server.HibernateUtils.generateSchema(HibernateUtils.java:49)
	at de.zeunerds.meat.server.usermanagement.access.AccountAccessTest.setUp(AccountAccessTest.java:18)
	at junit.framework.TestCase.runBare(TestCase.java:132)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framework.TestSuite.runTest(TestSuite.java:243)
	at junit.framework.TestSuite.run(TestSuite.java:238)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:83)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)
09-09 19:42:22 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "TEST" not found; SQL statement:
insert into person(account_mapping_fkey, name, creator_fkey) values (1, test, 1) [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.command.dml.Insert.prepare(Insert.java:231)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at net.sourceforge.sqlexplorer.dbproduct.AbstractDatabaseProduct.executeQuery(AbstractDatabaseProduct.java:75)
	at net.sourceforge.sqlexplorer.sqlpanel.SQLExecution.doExecution(SQLExecution.java:219)
	at net.sourceforge.sqlexplorer.sqlpanel.AbstractSQLExecution.run(AbstractSQLExecution.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
09-09 19:43:07 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "test" not found; SQL statement:
insert into person(account_mapping_fkey, name, creator_fkey) values (1, "test", 1) [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.command.dml.Insert.prepare(Insert.java:231)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at net.sourceforge.sqlexplorer.dbproduct.AbstractDatabaseProduct.executeQuery(AbstractDatabaseProduct.java:75)
	at net.sourceforge.sqlexplorer.sqlpanel.SQLExecution.doExecution(SQLExecution.java:219)
	at net.sourceforge.sqlexplorer.sqlpanel.AbstractSQLExecution.run(AbstractSQLExecution.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
09-09 19:43:20 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "test" not found; SQL statement:
insert into person (account_mapping_fkey, name, creator_fkey) values (1, "test", 1) [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.command.dml.Insert.prepare(Insert.java:231)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at net.sourceforge.sqlexplorer.dbproduct.AbstractDatabaseProduct.executeQuery(AbstractDatabaseProduct.java:75)
	at net.sourceforge.sqlexplorer.sqlpanel.SQLExecution.doExecution(SQLExecution.java:219)
	at net.sourceforge.sqlexplorer.sqlpanel.AbstractSQLExecution.run(AbstractSQLExecution.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
09-09 19:43:31 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Column "test" not found; SQL statement:
insert into person (account_mapping_fkey, name, creator_fkey) values (1, "test", 1) [42122-168]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.expression.ExpressionColumn.optimize(ExpressionColumn.java:138)
	at org.h2.command.dml.Insert.prepare(Insert.java:231)
	at org.h2.command.Parser.prepareCommand(Parser.java:218)
	at org.h2.engine.Session.prepareLocal(Session.java:415)
	at org.h2.engine.Session.prepareCommand(Session.java:364)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1109)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:164)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at net.sourceforge.sqlexplorer.dbproduct.AbstractDatabaseProduct.executeQuery(AbstractDatabaseProduct.java:75)
	at net.sourceforge.sqlexplorer.sqlpanel.SQLExecution.doExecution(SQLExecution.java:219)
	at net.sourceforge.sqlexplorer.sqlpanel.AbstractSQLExecution.run(AbstractSQLExecution.java:112)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
